import './globals.css'
import '../sections/Hero/Hero.scss'
import type { Metadata } from 'next'
import Navbar from '@/layout/Navbar'
import Footer from '@/layout/Footer'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={'body'}>
      <Navbar/>
        {children}
      <Footer/>
      </body>
    </html>
  )
}
